In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import OneHotEncoder
from sklearn.impute import SimpleImputer

from sklearn.linear_model import LinearRegression
from sklearn import metrics
from sklearn import ensemble, tree, linear_model
from sklearn.metrics import r2_score, mean_squared_error
from sklearn.model_selection import train_test_split, cross_val_score

In [2]:
df = pd.read_csv('../../../data/kc_house_data.csv')

In [3]:
df.corr().sort_values('price')

,id,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,grade,sqft_above,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
zipcode,-0.008211,-0.053402,-0.154092,-0.204786,-0.199802,-0.129586,-0.059541,0.031057,0.085277,0.002888,-0.185771,-0.261570,-0.347210,0.069846,1.000000,0.266742,-0.564259,-0.279299,-0.147294
id,1.000000,-0.016772,0.001150,0.005162,-0.012241,-0.131911,0.018608,-0.004176,0.011592,-0.023803,0.008188,-0.010799,0.021617,-0.012010,-0.008211,-0.001798,0.020672,-0.002701,-0.138557
long,0.020672,0.022036,0.132054,0.224903,0.241214,0.230227,0.125943,-0.039864,-0.077894,-0.105877,0.200341,0.344842,0.409993,-0.072156,-0.564259,-0.135371,1.000000,0.335626,0.255586
condition,-0.023803,0.036056,0.026496,-0.126479,-0.059445,-0.008830,-0.264075,0.017642,0.045735,1.000000,-0.146896,-0.158904,-0.361592,-0.061858,0.002888,-0.015102,-0.105877,-0.093072,-0.003126
yr_built,0.021617,0.053953,0.155670,0.507173,0.318152,0.052946,0.489193,-0.026079,-0.054564,-0.361592,0.447865,0.424037,1.000000,-0.225209,-0.347210,-0.148370,0.409993,0.326377,0.070777
sqft_lot15,-0.138557,0.082845,0.030690,0.088303,0.184342,0.718204,-0.010722,0.032002,0.073332,-0.003126,0.120981,0.195077,0.070777,0.003852,-0.147294,-0.086139,0.255586,0.183515,1.000000
sqft_lot,-0.131911,0.089876,0.032471,0.088373,0.173453,1.000000,-0.004814,0.023143,0.075298,-0.008830,0.114731,0.184139,0.052946,0.004513,-0.129586,-0.085514,0.230227,0.144763,0.718204
yr_renovated,-0.012010,0.129599,0.018495,0.051050,0.055660,0.004513,0.003535,0.087244,0.100964,-0.061858,0.016669,0.022137,-0.225209,1.000000,0.069846,0.032145,-0.072156,-0.000247,0.003852
floors,0.018608,0.256804,0.177944,0.502582,0.353953,-0.004814,1.000000,0.021883,0.028436,-0.264075,0.458794,0.523989,0.489193,0.003535,-0.059541,0.049239,0.125943,0.280102,-0.010722
waterfront,-0.004176,0.276295,-0.002386,0.067282,0.110230,0.023143,0.021883,1.000000,0.406654,0.017642,0.087383,0.075463,-0.026079,0.087244,0.031057,-0.012772,-0.039864,0.088860,0.032002
lat,-0.001798,0.306692,-0.009951,0.024280,0.052155,-0.085514,0.049239,-0.012772,0.006141,-0.015102,0.113575,-0.001199,-0.148370,0.032145,0.266742,1.000000,-0.135371,0.048679,-0.086139
bedrooms,0.001150,0.308787,1.000000,0.514508,0.578212,0.032471,0.177944,-0.002386,0.078523,0.026496,0.356563,0.479386,0.155670,0.018495,-0.154092,-0.009951,0.132054,0.393406,0.030690
view,0.011592,0.395734,0.078523,0.186451,0.282532,0.075298,0.028436,0.406654,1.000000,0.045735,0.249727,0.166299,-0.054564,0.100964,0.085277,0.006141,-0.077894,0.279561,0.073332
bathrooms,0.005162,0.525906,0.514508,1.000000,0.755758,0.088373,0.502582,0.067282,0.186451,-0.126479,0.665838,0.686668,0.507173,0.051050,-0.204786,0.024280,0.224903,0.569884,0.088303
sqft_living15,-0.002701,0.585241,0.393406,0.569884,0.756402,0.144763,0.280102,0.088860,0.279561,-0.093072,0.713867,0.731767,0.326377,-0.000247,-0.279299,0.048679,0.335626,1.000000,0.183515
sqft_above,-0.010799,0.605368,0.479386,0.686668,0.876448,0.184139,0.523989,0.075463,0.166299,-0.158904,0.756073,1.000000,0.424037,0.022137,-0.261570,-0.001199,0.344842,0.731767,0.195077
grade,0.008188,0.667951,0.356563,0.665838,0.762779,0.114731,0.458794,0.087383,0.249727,-0.146896,1.000000,0.756073,0.447865,0.016669,-0.185771,0.113575,0.200341,0.713867,0.120981
sqft_living,-0.012241,0.701917,0.578212,0.755758,1.000000,0.173453,0.353953,0.110230,0.282532,-0.059445,0.762779,0.876448,0.318152,0.055660,-0.199802,0.052155,0.241214,0.756402,0.184342
price,-0.016772,1.000000,0.308787,0.525906,0.701917,0.089876,0.256804,0.276295,0.395734,0.036056,0.667951,0.605368,0.053953,0.129599,-0.053402,0.306692,0.022036,0.585241,0.082845

In [4]:
#df = df.drop(columns=['id', 'sqft_lot', 'waterfront', 'view', 'sqft_above', 'yr_built', 'yr_renovated', 'zipcode', 'lat', 'long', 'sqft_living15', 'sqft_lot15', 'condition', 'bedrooms'])

In [5]:
df.columns = df.columns.str.replace(' ', '')
df.columns= df.columns.str.lower()

In [6]:
df['winter_spring_summer_fall'] = df['date'].str[0:2]

In [7]:
df['winter_spring_summer_fall'] = df['winter_spring_summer_fall'].replace(['1/'], '1')
df['winter_spring_summer_fall'] = df['winter_spring_summer_fall'].replace(['2/'], '1')
df['winter_spring_summer_fall'] = df['winter_spring_summer_fall'].replace(['3/'], '2')
df['winter_spring_summer_fall'] = df['winter_spring_summer_fall'].replace(['4/'], '2')
df['winter_spring_summer_fall'] = df['winter_spring_summer_fall'].replace(['5/'], '2')
df['winter_spring_summer_fall'] = df['winter_spring_summer_fall'].replace(['6/'], '3')
df['winter_spring_summer_fall'] = df['winter_spring_summer_fall'].replace(['7/'], '3')
df['winter_spring_summer_fall'] = df['winter_spring_summer_fall'].replace(['8/'], '3')
df['winter_spring_summer_fall'] = df['winter_spring_summer_fall'].replace(['9/'], '4')
df['winter_spring_summer_fall'] = df['winter_spring_summer_fall'].replace(['10'], '4')
df['winter_spring_summer_fall'] = df['winter_spring_summer_fall'].replace(['11'], '4')
df['winter_spring_summer_fall'] = df['winter_spring_summer_fall'].replace(['12'], '1')

In [8]:
df['winter_spring_summer_fall'] = df['winter_spring_summer_fall'].astype(int)

In [9]:
df['sqft_basement'] = pd.to_numeric(df.sqft_basement, errors='coerce')

In [10]:
df['basement'] = df['sqft_basement'] > 0

In [11]:
df['log_price'] = np.log(df['price'])
#df['log_price'] = np.power((df['price']),1/10)

In [12]:
df = df.drop(columns=['date', 'sqft_basement'])

In [13]:
df = df.dropna()

In [14]:
df

,id,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,...,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15,winter_spring_summer_fall,basement,log_price
1,6414100192,538000.0,3,2.25,2570,7242,2.0,0.0,0.0,3,...,1951,1991.0,98125,47.7210,-122.319,1690,7639,1,True,13.195614
3,2487200875,604000.0,4,3.00,1960,5000,1.0,0.0,0.0,5,...,1965,0.0,98136,47.5208,-122.393,1360,5000,1,True,13.311329
4,1954400510,510000.0,3,2.00,1680,8080,1.0,0.0,0.0,3,...,1987,0.0,98074,47.6168,-122.045,1800,7503,1,False,13.142166
5,7237550310,1230000.0,4,4.50,5420,101930,1.0,0.0,0.0,3,...,2001,0.0,98053,47.6561,-122.005,4760,101930,2,True,14.022525
6,1321400060,257500.0,3,2.25,1715,6819,2.0,0.0,0.0,3,...,1995,0.0,98003,47.3097,-122.327,2238,6819,3,False,12.458775
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21591,2997800021,475000.0,3,2.50,1310,1294,2.0,0.0,0.0,3,...,2008,0.0,98116,47.5773,-122.409,1330,1265,1,True,13.071070
21592,263000018,360000.0,3,2.50,1530,1131,3.0,0.0,0.0,3,...,2009,0.0,98103,47.6993,-122.346,1530,1509,2,False,12.793859
21593,6600060120,400000.0,4,2.50,2310,5813,2.0,0.0,0.0,3,...,2014,0.0,98146,47.5107,-122.362,1830,7200,1,False,12.899220
21594,1523300141,402101.0,2,0.75,1020,1350,2.0,0.0,0.0,3,...,2009,0.0,98144,47.5944,-122.299,1020,2007,3,False,12.904459
21596,1523300157,325000.0,2,0.75,1020,1076,2.0,0.0,0.0,3,...,2008,0.0,98144,47.5941,-122.299,1020,1357,4,False,12.691580

In [15]:
X = df[['bathrooms', 'sqft_living', 'floors', 'basement', 'grade', 'bedrooms', 'condition', 'view', 'waterfront', 'sqft_living15', 'sqft_lot15', 'sqft_lot', 'yr_renovated', 'yr_built', 'winter_spring_summer_fall', 'lat', 'long']]
y = df['log_price']

In [16]:
slr = LinearRegression()
slr.fit(X, y)

LinearRegression()

In [17]:
print(slr.intercept_)
print(slr.coef_)

-49.12933663612394
[ 6.46096145e-02  1.33633402e-04  7.87680677e-02  4.13789204e-02
  1.59036544e-01 -1.08042976e-02  6.75075335e-02  5.65332766e-02
  3.88999417e-01  1.05492034e-04 -2.29610197e-07  4.50761927e-07
  4.15587640e-05 -3.20741141e-03 -9.32003313e-03  1.34950153e+00
 -1.75832382e-02]

In [18]:
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=5)
print(len(X_train), len(X_test), len(y_train), len(y_test))

11821 3941 11821 3941

In [28]:
mlr_split = LinearRegression()

#fit
mlr_split.fit(X_train, y_train)

# calculate predictions on training and test sets
y_hat_train = mlr_split.predict(X_train)
y_hat_test = mlr_split.predict(X_test)

#compare MSE for the predicted training and test values 
train_mse = mean_squared_error(np.exp(y_train), np.log(y_hat_train))
test_mse = mean_squared_error(np.exp(y_test), y_hat_test)
print('Train Mean Squarred Error:', train_mse)
print('Test Mean Squarred Error:', test_mse)

print('Train score:', mlr_split.score(X_train, y_train))
print('Test score:', mlr_split.score(X_test, y_test))

Train Mean Squarred Error: 430426831324.27716
Test Mean Squarred Error: 434966424704.0428
Train score: 0.7704577770204251
Test score: 0.7711288848009814

In [29]:
def get_score(prediction, lables):    
    print('R2: {}'.format(r2_score(prediction, lables)))
    print('RMSE: {}'.format(np.sqrt(mean_squared_error(prediction, lables))))

In [30]:
def train_test(estimator, x_trn, x_tst, y_trn, y_tst):
    prediction_train = estimator.predict(x_trn)
    # Printing estimator
    print(estimator)
    # Printing train scores
    get_score(prediction_train, y_trn)
    prediction_test = estimator.predict(x_tst)
    # Printing test scores
    print("Test")
    get_score(prediction_test, y_tst)

In [31]:
GBest = ensemble.GradientBoostingRegressor(n_estimators=3000, learning_rate=0.05, max_depth=3, max_features='sqrt',
                                               min_samples_leaf=15, min_samples_split=10, loss='huber').fit(X_train, y_train)
train_test(GBest, X_train, X_test, y_train, y_test)

GradientBoostingRegressor(learning_rate=0.05, loss='huber', max_features='sqrt',
                          min_samples_leaf=15, min_samples_split=10,
                          n_estimators=3000)
R2: 0.9269961878643813
RMSE: 0.1352113365793906
Test
R2: 0.8865219491998817
RMSE: 0.164823870871658

In [32]:
scores = cross_val_score(GBest, X_test, y_test, cv=5)
print("Accuracy: %0.2f (+/- %0.2f)" % (scores.mean(), scores.std() * 2))

Accuracy: 0.89 (+/- 0.02)